In [1]:
Countries <- read.csv('http://manctsui.github.io/datasets/countries.csv')

In [ ]:
head(Countries)

  Country        Region               Population Area..sq..mi..
1 Afghanistan    ASIA (EX. NEAR EAST) 31056997    647500
2 Albania        EASTERN EUROPE        3581655     28748
3 Algeria        NORTHERN AFRICA      32930091   2381740
4 American Samoa OCEANIA                 57794       199
5 Andorra        WESTERN EUROPE          71201       468
6 Angola         SUB-SAHARAN AFRICA   12127071   1246700
  Pop..Density..per.sq..mi.. Coastline..coast.area.ratio. Net.migration
1  48.0                       0.00                         23.06
2 124.6                       1.26                         -4.93
3  13.8                       0.04                         -0.39
4 290.4                      58.29                        -20.71
5 152.1                       0.00                          6.60
6   9.7                       0.13                          0.00
  Infant.mortality..per.1000.births. GDP....per.capita. Literacy....
1 163.07                               700               36.0
2  21.52                              4500               86.5
3  31.00                              6000               70.0
4   9.27                              8000               97.0
5   4.05                             19000              100.0
6 191.19                              1900               42.0
  Phones..per.1000. Arable.... Crops.... Other.... Climate Birthrate Deathrate
1   3.2             12.13       0.22     87.65      1      46.60     20.34
2  71.2             21.09       4.42     74.49      3      15.11      5.22
3  78.1              3.22       0.25     96.53      1      17.14      4.61
4 259.5             10.00      15.00     75.00      2      22.46      3.27
5 497.2              2.22       0.00     97.78      3       8.71      6.25
6   7.8              2.41       0.24     97.35     NA      45.11     24.20
  Agriculture Industry Service
1 0.380       0.240    0.380
2 0.232       0.188    0.579
3 0.101       0.600    0.298
4    NA          NA       NA
5    NA          NA       NA
6 0.096       0.658    0.246

In [ ]:
length(Countries$Region == "EASTERN EUROPE" & Countries$Net.migration > 0)

[1] 227

In [22]:
Countries1 <- Countries[Countries$Region == "EASTERN EUROPE",]
Countries1 <- na.omit(Countries1)
Countries1 <- Countries1[order(Countries1$Net.migration, decreasing = T), ]
head(Countries1, 3)
# Czech Republic, Hungary and Romania

    Country        Region         Population Area..sq..mi..
54  Czech Republic EASTERN EUROPE 10235455    78866
93  Hungary        EASTERN EUROPE  9981334    93030
169 Romania        EASTERN EUROPE 22303552   237500
    Pop..Density..per.sq..mi.. Coastline..coast.area.ratio. Net.migration
54  129.8                      0.00                          0.97
93  107.3                      0.00                          0.86
169  93.9                      0.09                         -0.13
    Infant.mortality..per.1000.births. GDP....per.capita. Literacy....
54   3.93                              15700              99.9
93   8.57                              13900              99.4
169 26.43                               7000              98.4
    Phones..per.1000. Arable.... Crops.... Other.... Climate Birthrate
54  314.3             39.80      3.05      57.15     3        9.02
93  336.2             50.09      2.06      47.85     3        9.72
169 196.9             40.82      2.25      56.93     3       10.70
    Deathrate Agriculture Industry Service
54  10.59     0.034       0.393    0.573
93  13.11     0.037       0.312    0.651
169 11.77     0.101       0.350    0.549

In [23]:
Countries1 <- Countries[Countries$Region == "EASTERN EUROPE",]
Countries1 <- na.omit(Countries1)
Countries1 <- Countries1[order(Countries1$Net.migration), ]
head(Countries1, 3)
# Albania, Bulgaria, and Poland

    Country  Region         Population Area..sq..mi..
2   Albania  EASTERN EUROPE  3581655    28748
31  Bulgaria EASTERN EUROPE  7385367   110910
164 Poland   EASTERN EUROPE 38536869   312685
    Pop..Density..per.sq..mi.. Coastline..coast.area.ratio. Net.migration
2   124.6                      1.26                         -4.93
31   66.6                      0.32                         -4.58
164 123.3                      0.16                         -0.49
    Infant.mortality..per.1000.births. GDP....per.capita. Literacy....
2   21.52                               4500              86.5
31  20.55                               7600              98.6
164  8.51                              11100              99.8
    Phones..per.1000. Arable.... Crops.... Other.... Climate Birthrate
2    71.2             21.09      4.42      74.49     3       15.11
31  336.3             40.02      1.92      58.06     3        9.65
164 306.3             45.91      1.12      52.97     3        9.85
    Deathrate Agriculture Industry Service
2    5.22     0.232       0.188    0.579
31  14.27     0.093       0.304    0.603
164  9.89     0.050       0.311    0.640

In [ ]:
Countries$Country[is.na(Countries$Net.migration) | Countries$Net.migration == 0]

 [1] "Angola"               "Aruba"                "Belize"
 [4] "Benin"                "Bhutan"               "Botswana"
 [7] "Burkina Faso"         "Cambodia"             "Cameroon"
[10] "Central African Rep." "Chile"                "Comoros"
[13] "Congo, Dem. Rep. "    "Cook Islands"         "Djibouti"
[16] "East Timor"           "Equatorial Guinea"    "Eritrea"
[19] "Ethiopia"             "Gabon"                "Gibraltar"
[22] "Guam"                 "Indonesia"            "Iraq"
[25] "Japan"                "Kiribati"             "Korea, North "
[28] "Korea, South "        "Laos"                 "Lebanon"
[31] "Liberia"              "Libya"                "Madagascar"
[34] "Malawi"               "Malaysia"             "Maldives"
[37] "Mauritania"           "Mongolia"             "Montserrat"
[40] "Mozambique"           "Namibia"              "Nauru"
[43] "Nepal"                "New Caledonia"        "Papua New Guinea"
[46] "Reunion"              "Rwanda"               "Saint Helena"
[49] "Sierra Leone"         "Solomon Islands"      "Swaziland"
[52] "Syria"                "Taiwan"               "Thailand"
[55] "Togo"                 "Tonga"                "Turkey"
[58] "Tuvalu"               "Uganda"               "Vanuatu"
[61] "Wallis and Futuna"    "Western Sahara"       "Yemen"
[64] "Zambia"               "Zimbabwe"

In [25]:
row_cond <- Countries$Area..sq..mi.. > 2000000 | Countries$Population > 25000000
col_cond <- c("Country", "Population", "Area..sq..mi..")
Countries[row_cond, col_cond]

    Country           Population Area..sq..mi..
1   Afghanistan         31056997   647500
3   Algeria             32930091  2381740
9   Argentina           39921833  2766890
12  Australia           20264082  7686850
17  Bangladesh         147365352   144000
28  Brazil             188078227  8511965
33  Burma               47382633   678500
37  Canada              33098932  9984670
43  China             1313973713  9596960
44  Colombia            43593035  1138910
46  Congo, Dem. Rep.    62660551  2345410
61  Egypt               78887007  1001450
66  Ethiopia            74777981  1127127
70  France              60876136   547030
77  Germany             82422299   357021
81  Greenland              56361  2166086
95  India             1095351995  3287590
96  Indonesia          245452739  1919440
97  Iran                68688433  1648000
98  Iraq                26783383   437072
102 Italy               58133509   301230
104 Japan              127463611   377835
107 Kazakhstan          15233244  2717300
108 Kenya               34707817   582650
111 Korea, South        48846823    98480
136 Mexico             107449525  1972550
142 Morocco             33241259   446550
146 Nepal               28287147   147181
153 Nigeria            131859731   923768
157 Pakistan           165803560   803940
162 Peru                28302603  1285220
163 Philippines         89468677   300000
164 Poland              38536869   312685
170 Russia             142893540 17075200
180 Saudi Arabia        27019731  1960582
190 South Africa        44187637  1219912
191 Spain               40397842   504782
193 Sudan               41236378  2505810
201 Tanzania            37445392   945087
202 Thailand            64631595   514000
207 Turkey              70413958   780580
211 Uganda              28195754   236040
212 Ukraine             46710816   603700
214 United Kingdom      60609153   244820
215 United States      298444215  9631420
217 Uzbekistan          27307134   447400
219 Venezuela           25730435   912050
220 Vietnam             84402966   329560

In [28]:
row_cond <- Countries$Birthrate < Countries$Deathrate
length(Countries[row_cond, ]) # 20
length(is.na(Countries$Birthrate) | Countries$Birthrate == 0 | is.na(Countries$Deathrate) | Countries$Deathrate == 0) # 227

[1] 20

[1] 227

In [ ]:
Countries$Natural_population_change = (Countries$Birthrate - Countries$Deathrate)
Countries$Natural_population_change

In [34]:
head(Countries[order(Countries$Population, decreasing = T), "Country"], 3)

[1] "China"         "India"         "United States"

In [35]:
Countries[Countries$Population > 298444215*0.3, "Country"]

 [1] "Bangladesh"    "Brazil"        "China"         "India"
 [5] "Indonesia"     "Japan"         "Mexico"        "Nigeria"
 [9] "Pakistan"      "Russia"        "United States"

In [37]:
aggregate(Population ~ Country, data = Countries, FUN = mean)

    Country              Population
1   Afghanistan           31056997
2   Albania                3581655
3   Algeria               32930091
4   American Samoa           57794
5   Andorra                  71201
6   Angola                12127071
7   Anguilla                 13477
8   Antigua & Barbuda        69108
9   Argentina             39921833
10  Armenia                2976372
11  Aruba                    71891
12  Australia             20264082
13  Austria                8192880
14  Azerbaijan             7961619
15  Bahamas, The            303770
16  Bahrain                 698585
17  Bangladesh           147365352
18  Barbados                279912
19  Belarus               10293011
20  Belgium               10379067
21  Belize                  287730
22  Benin                  7862944
23  Bermuda                  65773
24  Bhutan                 2279723
25  Bolivia                8989046
26  Bosnia & Herzegovina   4498976
27  Botswana               1639833
28  Brazil               188078227
29  British Virgin Is.       23098
30  Brunei                  379444
⋮   ⋮                    ⋮
198 Syria                 18881361
199 Taiwan                23036087
200 Tajikistan             7320815
201 Tanzania              37445392
202 Thailand              64631595
203 Togo                   5548702
204 Tonga                   114689
205 Trinidad & Tobago      1065842
206 Tunisia               10175014
207 Turkey                70413958
208 Turkmenistan           5042920
209 Turks & Caicos Is        21152
210 Tuvalu                   11810
211 Uganda                28195754
212 Ukraine               46710816
213 United Arab Emirates   2602713
214 United Kingdom        60609153
215 United States        298444215
216 Uruguay                3431932
217 Uzbekistan            27307134
218 Vanuatu                 208869
219 Venezuela             25730435
220 Vietnam               84402966
221 Virgin Islands          108605
222 Wallis and Futuna        16025
223 West Bank              2460492
224 Western Sahara          273008
225 Yemen                 21456188
226 Zambia                11502010
227 Zimbabwe              12236805