In [4]:
library(tidyverse)
df <- read.csv("http://manctsui.github.io/datasets/countries.csv")
head(df, 5)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.1     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.3     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

  Country        Region               Population Area..sq..mi..
1 Afghanistan    ASIA (EX. NEAR EAST) 31056997    647500
2 Albania        EASTERN EUROPE        3581655     28748
3 Algeria        NORTHERN AFRICA      32930091   2381740
4 American Samoa OCEANIA                 57794       199
5 Andorra        WESTERN EUROPE          71201       468
  Pop..Density..per.sq..mi.. Coastline..coast.area.ratio. Net.migration
1  48.0                       0.00                         23.06
2 124.6                       1.26                         -4.93
3  13.8                       0.04                         -0.39
4 290.4                      58.29                        -20.71
5 152.1                       0.00                          6.60
  Infant.mortality..per.1000.births. GDP....per.capita. Literacy....
1 163.07                               700               36.0
2  21.52                              4500               86.5
3  31.00                              6000               70.0
4   9.27                              8000               97.0
5   4.05                             19000              100.0
  Phones..per.1000. Arable.... Crops.... Other.... Climate Birthrate Deathrate
1   3.2             12.13       0.22     87.65     1       46.60     20.34
2  71.2             21.09       4.42     74.49     3       15.11      5.22
3  78.1              3.22       0.25     96.53     1       17.14      4.61
4 259.5             10.00      15.00     75.00     2       22.46      3.27
5 497.2              2.22       0.00     97.78     3        8.71      6.25
  Agriculture Industry Service
1 0.380       0.240    0.380
2 0.232       0.188    0.579
3 0.101       0.600    0.298
4    NA          NA       NA
5    NA          NA       NA

In [5]:
df |>
  filter(Region == "EASTERN EUROPE", Net.migration > 0) |>
  length()

[1] 20

In [6]:
df |>
  filter(Region == "EASTERN EUROPE") |>
  arrange(desc(Net.migration)) |>
  head(3)

  Country        Region         Population Area..sq..mi..
1 Croatia        EASTERN EUROPE  4494749   56542
2 Slovenia       EASTERN EUROPE  2010347   20273
3 Czech Republic EASTERN EUROPE 10235455   78866
  Pop..Density..per.sq..mi.. Coastline..coast.area.ratio. Net.migration
1  79.5                      10.32                        1.58
2  99.2                       0.23                        1.12
3 129.8                       0.00                        0.97
  Infant.mortality..per.1000.births. GDP....per.capita. Literacy....
1 6.84                               10600              98.5
2 4.45                               19000              99.7
3 3.93                               15700              99.9
  Phones..per.1000. Arable.... Crops.... Other.... Climate Birthrate Deathrate
1 420.4             26.09      2.27      71.65     NA      9.61      11.48
2 406.1              8.60      1.49      89.91     NA      8.98      10.31
3 314.3             39.80      3.05      57.15      3      9.02      10.59
  Agriculture Industry Service
1 0.070       0.308    0.622
2 0.028       0.369    0.603
3 0.034       0.393    0.573

In [7]:
df |>
  filter(Region == "EASTERN EUROPE") |>
  arrange(Net.migration) |>
  head(3)

  Country   Region         Population Area..sq..mi.. Pop..Density..per.sq..mi..
1 Albania   EASTERN EUROPE 3581655     28748         124.6
2 Bulgaria  EASTERN EUROPE 7385367    110910          66.6
3 Macedonia EASTERN EUROPE 2050554     25333          80.9
  Coastline..coast.area.ratio. Net.migration Infant.mortality..per.1000.births.
1 1.26                         -4.93         21.52
2 0.32                         -4.58         20.55
3 0.00                         -1.45         10.09
  GDP....per.capita. Literacy.... Phones..per.1000. Arable.... Crops....
1 4500               86.5          71.2             21.09      4.42
2 7600               98.6         336.3             40.02      1.92
3 6700                 NA         260.0             22.26      1.81
  Other.... Climate Birthrate Deathrate Agriculture Industry Service
1 74.49     3       15.11      5.22     0.232       0.188    0.579
2 58.06     3        9.65     14.27     0.093       0.304    0.603
3 75.93     3       12.02      8.77     0.118       0.319    0.563

In [8]:
df |>
  filter(Net.migration == NA | Net.migration == 0) |>
  select(Country)

   Country
1  Angola
2  Aruba
3  Belize
4  Benin
5  Bhutan
6  Botswana
7  Burkina Faso
8  Cambodia
9  Cameroon
10 Central African Rep.
11 Chile
12 Comoros
13 Congo, Dem. Rep.
14 Djibouti
15 East Timor
16 Equatorial Guinea
17 Eritrea
18 Ethiopia
19 Gabon
20 Gibraltar
21 Guam
22 Indonesia
23 Iraq
24 Japan
25 Kiribati
26 Korea, North
27 Korea, South
28 Laos
29 Lebanon
30 Liberia
⋮  ⋮
33 Malawi
34 Malaysia
35 Maldives
36 Mauritania
37 Mongolia
38 Montserrat
39 Mozambique
40 Namibia
41 Nauru
42 Nepal
43 New Caledonia
44 Papua New Guinea
45 Reunion
46 Rwanda
47 Saint Helena
48 Sierra Leone
49 Solomon Islands
50 Swaziland
51 Syria
52 Taiwan
53 Thailand
54 Togo
55 Tonga
56 Turkey
57 Tuvalu
58 Uganda
59 Vanuatu
60 Yemen
61 Zambia
62 Zimbabwe

In [9]:
df |>
  filter(Area..sq..mi.. > 2000000 | Population > 25000000) |>
  select(Country, Population, Area..sq..mi..)

   Country           Population Area..sq..mi..
1  Afghanistan         31056997   647500
2  Algeria             32930091  2381740
3  Argentina           39921833  2766890
4  Australia           20264082  7686850
5  Bangladesh         147365352   144000
6  Brazil             188078227  8511965
7  Burma               47382633   678500
8  Canada              33098932  9984670
9  China             1313973713  9596960
10 Colombia            43593035  1138910
11 Congo, Dem. Rep.    62660551  2345410
12 Egypt               78887007  1001450
13 Ethiopia            74777981  1127127
14 France              60876136   547030
15 Germany             82422299   357021
16 Greenland              56361  2166086
17 India             1095351995  3287590
18 Indonesia          245452739  1919440
19 Iran                68688433  1648000
20 Iraq                26783383   437072
21 Italy               58133509   301230
22 Japan              127463611   377835
23 Kazakhstan          15233244  2717300
24 Kenya               34707817   582650
25 Korea, South        48846823    98480
26 Mexico             107449525  1972550
27 Morocco             33241259   446550
28 Nepal               28287147   147181
29 Nigeria            131859731   923768
30 Pakistan           165803560   803940
31 Peru                28302603  1285220
32 Philippines         89468677   300000
33 Poland              38536869   312685
34 Russia             142893540 17075200
35 Saudi Arabia        27019731  1960582
36 South Africa        44187637  1219912
37 Spain               40397842   504782
38 Sudan               41236378  2505810
39 Tanzania            37445392   945087
40 Thailand            64631595   514000
41 Turkey              70413958   780580
42 Uganda              28195754   236040
43 Ukraine             46710816   603700
44 United Kingdom      60609153   244820
45 United States      298444215  9631420
46 Uzbekistan          27307134   447400
47 Venezuela           25730435   912050
48 Vietnam             84402966   329560

In [10]:
df |>
  filter(Deathrate < Birthrate) |>
  length()

df |>
  filter(is.na(Deathrate) | is.na(Birthrate)) |>
  select(Country)

[1] 20

  Country
1 Cook Islands
2 Serbia
3 Wallis and Futuna
4 Western Sahara

In [12]:
df$Natural_population_change <- df$Birthrate - df$Deathrate
head(df$Natural_population_change, 5)

[1] 26.26  9.89 12.53 19.19  2.46

In [13]:
df |>
  arrange(desc(Population)) |>
  head(3)

  Country       Region               Population Area..sq..mi..
1 China         ASIA (EX. NEAR EAST) 1313973713 9596960
2 India         ASIA (EX. NEAR EAST) 1095351995 3287590
3 United States NORTHERN AMERICA      298444215 9631420
  Pop..Density..per.sq..mi.. Coastline..coast.area.ratio. Net.migration
1 136.9                      0.15                         -0.40
2 333.2                      0.21                         -0.07
3  31.0                      0.21                          3.41
  Infant.mortality..per.1000.births. GDP....per.capita. Literacy.... ⋯
1 24.18                               5000              90.9         ⋯
2 56.29                               2900              59.5         ⋯
3  6.50                              37800              97.0         ⋯
  Arable.... Crops.... Other.... Climate Birthrate Deathrate Agriculture
1 15.40      1.25      83.35     1.5     13.25     6.97      0.125
2 54.40      2.74      42.86     2.5     22.01     8.18      0.186
3 19.13      0.22      80.65     3.0     14.14     8.26      0.010
  Industry Service Natural_population_change
1 0.473    0.403    6.28
2 0.276    0.538   13.83
3 0.204    0.787    5.88

In [17]:
df |>
  filter(Population > 298444215*0.3) |>
  head(3)

  Country    Region               Population Area..sq..mi..
1 Bangladesh ASIA (EX. NEAR EAST)  147365352  144000
2 Brazil     LATIN AMER. & CARIB   188078227 8511965
3 China      ASIA (EX. NEAR EAST) 1313973713 9596960
  Pop..Density..per.sq..mi.. Coastline..coast.area.ratio. Net.migration
1 1023.4                     0.40                         -0.71
2   22.1                     0.09                         -0.03
3  136.9                     0.15                         -0.40
  Infant.mortality..per.1000.births. GDP....per.capita. Literacy.... ⋯
1 62.60                              1900               43.1         ⋯
2 29.61                              7600               86.4         ⋯
3 24.18                              5000               90.9         ⋯
  Arable.... Crops.... Other.... Climate Birthrate Deathrate Agriculture
1 62.11      3.07      34.82     2.0     29.80     8.27      0.199
2  6.96      0.90      92.15     2.0     16.56     6.17      0.084
3 15.40      1.25      83.35     1.5     13.25     6.97      0.125
  Industry Service Natural_population_change
1 0.198    0.603   21.53
2 0.400    0.516   10.39
3 0.473    0.403    6.28

[1] 1

In [18]:
aggregate(Population ~ Region, data = df, FUN = mean)

   Region               Population
1  ASIA (EX. NEAR EAST) 131713651
2  BALTICS                2394991
3  C.W. OF IND. STATES   23340129
4  EASTERN EUROPE         9992893
5  LATIN AMER. & CARIB   12484991
6  NEAR EAST             12191774
7  NORTHERN AFRICA       26901189
8  NORTHERN AMERICA      66334461
9  OCEANIA                1577698
10 SUB-SAHARAN AFRICA    14694843
11 WESTERN EUROPE        14155000